spring:
  application:
    name: pblb

  datasource:
    url: jdbc:postgresql://localhost:5432/pblb
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Genera/actualiza las tablas automáticamente
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: false  # Deshabilitamos liquibase por ahora ya que usaremos hibernate para generar la estructura

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ffc01dec03cf95
    password: f7d9848479d07f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.softwells.pblb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Configuraciones específicas de la aplicación
app:
  security:
    jwt:
      secret: realbetiscampeon
      expiration: 86400000  # 24 horas en milisegundos

# Dirección de correo para el remitente
mail:
  from:
    address: ${spring.mail.username}
